version: '3.9'

services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: node:20.14-alpine
    working_dir: /app
    volumes: 
      - ../books_counter:/app
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    ports:
       - 80:3001
    command: npm run dev
    depends_on: 
      - storage